@startuml

' Основное описание Диаграммы классов: https://plantuml.com/ru/class-diagram
!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/dist/all.puml

'skinparam linetype ortho

header 3L 
title ER от 20.01.2025
caption Схема адресов и телефонов для обмена с РС
footer 2025

package РС <<folder>> { 

}

package ОбъектнаяМодельСправочниковДляОбменаРС <<folder>> #ffff99 { 
  _Справочник(АдресаРС, "Адреса РС (новый справочник)"){
        *Владелец
        КодРС
        ...ВсяИнформацияПоСправочнику
    }

  _Справочник(ТелефоныРС, "Телефоны РС (новый справочник)"){
        *Владелец
        КодРС
        ...ВсяИнформацияПоСправочнику
    }

}

  _Справочник(ФизическиеЛица, "Физические лица")
  _Справочник(Контрагенты, "Контрагенты"){
    *Ссылка
    Партнер
  }
  _Справочник(Партнеры, "Партнеры")
 
_РегистрСведений(ллл_ДополнительнаяИнформацияКИ, "Дополнительная информация КИ (3L)") {
        <$d> Объект
        <$d> ВидКонтактнойИнформации
        <$d> КодСтроки
        <$r> АналитикаДляРС
    }

' Связи с регистром доп.информации
ФизическиеЛица --> ллл_ДополнительнаяИнформацияКИ::Объект
Контрагенты --> ллл_ДополнительнаяИнформацияКИ::Объект
'Партнеры --> ллл_ДополнительнаяИнформацияКИ::Объект

АдресаРС --> ллл_ДополнительнаяИнформацияКИ::АналитикаДляРС
ТелефоныРС --> ллл_ДополнительнаяИнформацияКИ::АналитикаДляРС

Контрагенты --- АдресаРС::Владелец
Контрагенты --- ТелефоныРС::Владелец
ФизическиеЛица --- АдресаРС::Владелец
ФизическиеЛица --- ТелефоныРС::Владелец
Партнеры --- Контрагенты::Партнер

ОбъектнаяМодельСправочниковДляОбменаРС --> РС

@enduml